### ISSUE TITLE
Package configuration should be standard

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview-timeline-components#11]
It looks like the `main` field in `package.json` points to a file that doesn't exist. It looks like it was originally a build result, but the build results are different now. Regardless, the entry point shouldn't be in a build result, if we can help it.

It also looks like this package isn't making use of the `dependencies` field in `package.json`, which means that all dependencies are listed as `devDependencies` and require a `build` step to be run when this package is included as a dependency itself. That's error prone, and breaks npm workflows and dependency graph optimizations. We should follow the standard project structure here and move `import`ed dependencies to the `dependency` key, allowing them to be installed in a normal npm workflow. This package shouldn't need a separate `gulp` step to build it.

**Comment by ZachTRice** [comment]
This was overhauled in the module-loaders (worldview 2.0) work.
