### ISSUE TITLE
Render Markdown Directly in Components

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview-timeline-components#28]
Instead of converting markdown files into HTML strings to render markdown into components, it would be nice to use something like [`react-markdown`](https://www.npmjs.com/package/react-markdown) directly. The would be safer, and allow us to skip the step we currently have of generating intermediary HTML files, in favor of using the markdown files directly.

This will be a fairly simple change, but since we're using `<sub>`/`<sup>` tags in our markdown, this is pending a fix for an issue that `react-markdown` has with rendering some inline HTML tags: https://github.com/rexxars/commonmark-react-renderer/issues/9

**Comment by ZachTRice** [comment]
Closing this issue since components will be deprecated soon. We can re-open this issue in the worldview repository if need be.
