### ISSUE TITLE
Add jshint file for es6 linting

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview-timeline-components#3]
During development, my jshint was not detecting es6. This needs to be specified in a .jshintrc file located in the root.

**Comment by Benjaki2** [comment]
Worldview-components uses ESlint. ESlint has better ES6 / react compatibility

**Comment by ZachTRice** [comment]
Ah right on. Could we create an eslint file in Worldview for consistency? I often have both wv and wv-components up in the same editor so the linters conflict.

**Comment by ZachTRice** [comment]
Looks like that would need to be added to package.json and if we do that then remove jshint?

**Comment by Benjaki2** [comment]
So we have an eslint file here: https://github.com/nasa-gibs/worldview-components/blob/master/src/scripts/.eslintrc

Good idea @ZachTRice 👍 .We will need to replace it in the package.json and the Gruntfile. I will make a new issue for that.

**Comment by ZachTRice** [comment]
I'm closing this issue since we aren't changing anything on wv-components and we have a ticket on wv to add eslint there.
