### ISSUE TITLE
Investigate CI failures

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview-timeline-components#37]
The latest builds have all failed CI tests with the error: `There was an error while trying to fetch the log.`

**Comment by Benjaki2** [comment]
@ZachTRice Is this issue just with WVC? Travis logs appear to show most Worldview branches passing.

**Comment by ZachTRice** [comment]
Yes, just worldview-components

**Comment by Benjaki2** [comment]
Cool, Thanks .I Was looking at this in waffles and didn't see it was a WVC issue.
